### ISSUE TITLE
Caracteristica: formulario para sacar turno

### ISSUE THREAD

**Issue by moradan** [LaWeaArgentina/Clinica-San-Camilo#15]
Diseár el formulario para sacar turnos.
El formulario para sacar turno debe permitir seleccionar una especialidad, un profesional, una fecha y un horario. 
Se porían seleccionar especialidad y profesional por separado en dos campos o ambos a la vez porque los profesionales van a estar guardados junto con una especialidad. La lista de profesionales/especialidades hay que levantarlas de la base de datos, y deben ser servidas por el backend.
Una vez enviado el formulario el backend debe validar si el turno se puede otorgar o no.
El front end debe mostrar una confirmación o rechazo que puede ser una página distinta al formulario con un link para regresar al formulario, o bien mostrando un parrafo de error en la misma página en que se saca el turno. Esto para que el usuario pueda volver a intentar sacar turno en caso de rechazo.

**Comment by moradan** [comment]
Me encantó el formulario que hiciste. En particular que los campos se vaya haciendo visibles a medida que lo completas.

Fijate en este link: [Time Picker](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time). Puede que este tipo de  \<input\> sea mas conveniente para seleccionar el horario. 

Decime que te parece.

**Comment by LaWeaArgentina** [comment]
La idea es que una vez esté integrado el back, los turnos que ya estén ocupados dentro de la fecha que se seleccione van a aparecer en rojo y no van a poder ser seleccionados. Otra cosa es que al dividir el día en 16 partes iguales predefinidas se vuelve mucho más fácil, por no decir posible, determinar la cantidad de turnos que se pueden sacar en un día y evitar que se puedan sacar múltiples turnos en horarios similares.

No creo que sea posible hacer todo esto con un input de HTML, por eso me decidí a hacerlo de esta forma.

**Comment by moradan** [comment]
Perfecto. Vamos bien. Si queres continuar trabajando en esa pagina, dale nomas. Por mi, ya esta lista. Este issue ya se puede cerrar.
